### ISSUE TITLE
Black screen at start - Android 10 - Huawei P40 Lite

### ISSUE THREAD

**Issue by Jenmet-cy** [skylersaleh/SkyEmu#215]
SkyEmu fails to initialize properly on my Huawei P40 Lite. It flashes the GUI for a short second, and then it immediately falls to black. This bug started to appear some months ago (specifically, when the binary size increased from ~2MB to ~15MB). Older versions work properly.

**Comment by skylersaleh** [comment]
I think this may be caused by the changes I added to support Chinese, Japanese, and Korean in the UI a few weeks ago. 

Can test these two builds and ensure that the one labeled "good" works correctly, and the one labeled "bad" black screens? 
[AndroidRelease-bad.zip](https://github.com/skylersaleh/SkyEmu/files/10422791/AndroidRelease-bad.zip)
[AndroidRelease-good.zip](https://github.com/skylersaleh/SkyEmu/files/10422793/AndroidRelease-good.zip)

Also, could I get you to try the latest android build (one that black screens) and see if the UI loads eventually if you leave it for a while (~10 mins)?

**Comment by Jenmet-cy** [comment]
Okay. Tested the two builds; the "bad" one stays in a black screen like the rest, and the "good" one starts and works properly.

`Also, could I get you to try the latest android build (the one that black screens) and see if the UI loads eventually if you leave it for a while (~10 mins)?`

Sure! I'll try it right now.

**Comment by Jenmet-cy** [comment]
Okay. I tested the latest build on my device for ~20 min. I didn't minimize it or use multitasking in this time. Unfortunately, the app was still showing a black screen after that time.

I can provide you a logcat in a few hours if needed. I would do it right now, but I don't have my PC in this moment.

**Comment by skylersaleh** [comment]
It would be great if you could provide a logcat.

**Comment by Jenmet-cy** [comment]
Okay. Here are the logs that I was able to take. One is from master, the other is from the "good" build, just for comparison. https://file.io/nmdF9vCdZqIg

**Comment by skylersaleh** [comment]
Thanks! I'll take a look at the logs. In the mean time can you test out this build here? 

I just made a bunch of optimizations to the unicode pipeline to make it faster and more memory efficient. It might fix things up if we are dealing with an issue caused by the font atlas texture being too large. 

[AndroidRelease-unicode-opt.zip](https://github.com/skylersaleh/SkyEmu/files/10429312/AndroidRelease-unicode-opt.zip)

**Comment by Jenmet-cy** [comment]
I just tested that build and it works properly again. Thanks!
