### ISSUE TITLE
Shrek 2 GBA: green blobs between screens

### ISSUE THREAD

**Issue by RetroEdit** [skylersaleh/SkyEmu#316]
In the menu transitions between the Books menu and the Chapter selection menu, there are random green blobs that don't appear on real console or mGBA. You can easily reproduce by loading the game, creating a new save slot, and skipping the intro cutscene by pressing 'Start' to get to the Book menu.

I've included a video below. First is SkyEmu `104c287`, second is NanoBoyAdvance `49c1403`, third is mGBA `6a31777`.

https://www.youtube.com/watch?v=61gzNH9H4C0

**Comment by fleroviux** [comment]
This triggers an edge-case in vertical sprite mosaic behavior. Basically because sprite mosaic is global and not relative to the top-left corner of the sprite, it is possible that when adjusting the local y-coordinate for mosaic (by calculating `spriteLocalY - spriteMosaicYCounter`) it becomes less than zero. In that case the hardware *seems* to clamp the value to zero, meaning that the first couple scanlines, where this is the case, all render the top scanline of the sprite instead of transparent pixels or something else.

Here's a basic test ROM:

[sprite-vmosaic.zip](https://github.com/skylersaleh/SkyEmu/files/12316722/sprite-vmosaic.zip)

The expected output is this:

![image](https://github.com/skylersaleh/SkyEmu/assets/13669774/2600586f-1615-426d-8263-ee04d0995386)

However NanoBoyAdvance (implementing this) currently slightly deviates from this and I'm not sure why:

![image](https://github.com/skylersaleh/SkyEmu/assets/13669774/2dc36d62-1237-4321-9e47-0162ce07882a)

**Comment by skylersaleh** [comment]
I submitted a partial fix to this. It should resolve the issues in shrek, but it doesn't pass Flero's torture test (although, it is much closer now) 

<img width="1392" alt="image" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/c2fac866-8070-4804-9a70-b55a9ab8ed62">

**Comment by RetroEdit** [comment]
As best I can tell without pixel-by-pixel comparison, the screen transitions look much more accurate now.
