### ISSUE TITLE
[Feature Request] Support for retroachievements.org

### ISSUE THREAD

**Issue by dochankpin** [skylersaleh/SkyEmu#36]
Hello everybody!

Greetings, I was wondering if it's possible,
for developers to add support for: retroachievements.org ?
It would be just perfect, playing the GB, GBC and GBA games,
unlocking the achievements of each specific game.

Another thing, in the future will there be an APK version
to install on android devices?
Thanks in advance for everyone's attention.
Bye see you later.

**Comment by skylersaleh** [comment]
Forking this feature request to only cover the retroachievements.org request. 
The request for an Android Native Build can be tracked here: https://github.com/skylersaleh/SkyEmu/issues/37

**Comment by skylersaleh** [comment]
This is now supported in dev 🎉

**Comment by RenanSD007** [comment]
Would it be possible to create an issue tracking everything missing related to RetroAchievements? Some suggestions that has on other emulators

• Unlock Sound
• [Optional] Change Popup Locations (Achievements, Trigger Icons, Leaderboards Submit/Fail)
• Encore Mode
• Test Unnoficial Achievements
• Show Save State on Hardcore Mode (even if cannot be loaded)

It also seems that the emulator does not send Rich Presence from the game to the website, and if it is added it can only be disabled in Softcore mode

**Comment by OFFTKP** [comment]
> Would it be possible to create an issue tracking everything missing related to RetroAchievements? Some suggestions that has on other emulators
> 
> • Unlock Sound • [Optional] Change Popup Locations (Achievements, Challenge Indicatiors, Leaderboards Submit/Fail) • Encore Mode • Test Unnoficial Achievements • Show Save State on Hardcore Mode (even if cannot be loaded)
> 
> It also seems that the emulator does not send Rich Presence from the game to the website, and if it is added it can only be disabled in Softcore mode

What is Encore mode and Unlock sound?

I did wanna change how we handle progress indicators as the current solution is ugly, but what would you change about challenge indicators or achievements? Pics from other emulators would help.

We have a todo list for nice things to have on the discord, I've added the "Show Save State on Hardcore Mode (even if cannot be loaded)"

I don't know about the rich presence, could you tell me more about it?

**Comment by RenanSD007** [comment]
Encore Mode would start a session with all achievements in locked state (even if they were previously unlocked on website, useful if the person wants to play everything again to record a walkthrough for example)

Unlock Sound would play a sound effect when an achievement is unlocked

In the case of Rich Presence, for example, it indicates where you are in the game and some other data, most games have this, the way it is now just sends something like "Playing Kirby's Dream Land 2", the same for any other game
![Screenshot_2024-08-13-16-53-26-478_com.kiwibrowser.browser.jpg](https://github.com/user-attachments/assets/9a446df6-dcc9-4b21-a9a9-f6f356ef9c6a)

**Comment by RenanSD007** [comment]
In the case of popup positioning, there is RetroArch and PPSSPP for example, like leaving the achievement unlock popup in the "Top Center or Top Right" instead of "Top Left" as it is now, more positioning for examples "Bottom Left, Center, Right"
![Screenshot_2024-08-13-17-01-47-538_com.sky.SkyEmu.jpg](https://github.com/user-attachments/assets/fd21043a-5510-4df9-a704-a79b882ad87c)

**Comment by RenanSD007** [comment]
In the case of popup positioning, there is RetroArch and PPSSPP for example, like leaving the achievement unlock popup in the "Top Center or Top Right" instead of "Top Left" as it is now, more positioning for examples "Bottom Left, Center, Right"
![Screenshot_2024-08-13-17-01-47-538_com.sky.SkyEmu.jpg](https://github.com/user-attachments/assets/fd21043a-5510-4df9-a704-a79b882ad87c)

In PPSSPP
![Screenshot_2024-08-13-17-15-26-122_org.ppsspp.ppsspp.jpg](https://github.com/user-attachments/assets/72408f5d-1c7f-4322-b53a-f9fd9b5f648c)

**Comment by RenanSD007** [comment]
In PPSSPP for example
![Screenshot_2024-08-13-17-15-26-122_org.ppsspp.ppsspp.jpg](https://github.com/user-attachments/assets/9aebeeb1-d128-4624-9b45-1bd1f393aa8c)

**Comment by OFFTKP** [comment]
Cool, thanks for the suggestions. Rich presence is on its way to being added, there was a bug so you pointing out it's missing helped me realize.

I'll add the rest of the features to the todo list, they are definitely possible
