### ISSUE TITLE
 [GBC] Pokemon crystal “This Game Pak is designed only for use on the Game Boy Color.” Error

### ISSUE THREAD

**Issue by Fishlerten45** [skylersaleh/SkyEmu#442]
The first time when I opened up Crystal it ran fine. But recently it has shown this error screen saying “ This Game Pak is designed only for use on the Game Boy Color.” I have tried many roms of the same game but it still says that error. Please help fix this.

**Comment by skylersaleh** [comment]
This happens when you launch a GBC game in GB (DMG) mode. 

Things to try: 

1) Make sure Force GB games to run in DMG mode is unchecked: 
<img width="323" alt="image" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/4e38012a-08d8-4faf-84f8-d9fdd6226d76">
2) Make sure you are either providing a GBC boot rom or are not providing a GB boot rom
<img width="312" alt="image" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/cb5e9396-f2ad-41db-bd35-3c2fa175db8e">

**Comment by Fishlerten45** [comment]
Ok I got it, thank you very much
