### ISSUE TITLE
Survival Kids (GBC) intro sequence has wrong color pallette 

### ISSUE THREAD

**Issue by jkjwong** [skylersaleh/SkyEmu#79]
When you first start up the game it says "Licensed by Nintendo" followed by the Konami logo. Both screens have wrong colors.

**Comment by skylersaleh** [comment]
This is now fixed in the dev branch. 
<img width="1392" alt="Screen Shot 2022-09-17 at 12 42 58 PM" src="https://user-images.githubusercontent.com/7118296/190874010-3618d5c5-088a-4c3d-88ac-deca672d25ec.png">

<img width="1392" alt="Screen Shot 2022-09-17 at 12 43 12 PM" src="https://user-images.githubusercontent.com/7118296/190874007-3cfee689-fac2-41a6-9103-5dc65aeb60e8.png">
